### ISSUE TITLE
Does huggingface contain mistralai functionality? 

### ISSUE THREAD

**Issue by mihalt** [mistralai/client-python#106]
I like functionality of `tools` and `is_json` in mistralai. Can I get the same and another mistralai features in huggingface mistral model?

**Comment by sophiamyang** [comment]
Closing the issue since it's inactive. Please feel free to reopen the issue if there are more concerns.

**Comment by mihalt** [comment]
> Hi there, I'm not sure I'm following, both open models `mistral-7b-instruct-v0.3` and `mixtral-8x22b-instruct-v0.1` have function calling too, you should be able to use it.

so, how to do the same as `tools` and `is_json` in huggingface? Can you give me script example?
