### ISSUE TITLE
[BUG CLIENT]: faulty logic in the function_calling.py examples

### ISSUE THREAD

**Issue by gwk** [mistralai/client-python#115]
### Python -VV

```shell
N/A
```

### Pip Freeze

```shell
N/A
```

### Reproduction Steps

I just read `examples/function_calling.py` and it appears that both functions have the `else` clause return the error case in the first iteration. 

https://github.com/mistralai/client-python/blob/c2bfb767f2222f4efc798f3cb9c19c9ab20b9029/examples/function_calling.py#L23
https://github.com/mistralai/client-python/blob/c2bfb767f2222f4efc798f3cb9c19c9ab20b9029/examples/function_calling.py#L31

### Expected Behavior

This seems clearly broken; the loop should iterate over all the records.

### Suggested Solutions

It seems to me that the else/return lines should be unindented one level (creating a Python for/else statement) or better, remove the `else` line and unindent the error case return to the function body level.

**Comment by fuegoio** [comment]
Thanks a lot for your report. Indeed it seems that our documentation has been updated a long time ago but we did not update this example. I fixed it in #116!
