### ISSUE TITLE
[BUG CLIENT]: Prompting Mixtral Article page resource

### ISSUE THREAD

**Issue by nmtimkul** [mistralai/client-python#150]
### Python -VV

```shell
Python -VV
```

### Pip Freeze

```shell
Pip freeze
```

### Reproduction Steps

The Prompting Capabilities resource file is not configured correctly on the Brave support articles page, it throws a 404 exception when called from your partner.

### Expected Behavior

What supposed to be a stream web service, when calling an HTML file from documents/ artist page, a different classpath resource file shows up as (404) from (https://docs.mistral.ai/guides/prompting-capabilities/) instead of (https://docs.mistral.ai/guides/prompting_capabilities/)

### Additional Context

I assume the service focuses on streamlining the HTML components and how the headers is configured, parts of the classpath file resources, depending on how they are amended to breadcrumbs, could be a clash from how the page wants to load data from a broken Uri.

### Suggested Solutions

From my knowledge; both Short and long UTF-8 encoding <meta> should be included for instances of users still using old browser(s).

<meta Content-Type: "text/html"; "charset=UTF-8" />

and also :

<meta charset="UTF-8" />

**Comment by GaspardBT** [comment]
Hi, thanks for opening an issue 🙇

I've created a ticket internally to look into it. I will close this issue as this repo is for the Python client.
