### ISSUE TITLE
[BUG CLIENT]: bad python-dateutil dependency specification

### ISSUE THREAD

**Issue by folkvir** [mistralai/client-python#158]
### Python -VV

```shell
.
```

### Pip Freeze

```shell
python-dateutil==2.9.0
```

### Reproduction Steps

1. Install `python-dateutil==2.9.0`
2. Install latest `mistralai==1.2.3`

Will block with conflict:
`mistralai 1.2.3 requires python-dateutil==2.8.2, but you'll have python-dateutil 2.9.0 which is incompatible.`

### Expected Behavior

The client should allow the version 2.9.0 of the `python-dateutil`. 
If there is no reason to lock the version `2.8.2` then you should not strictly specify the version.

### Suggested Solutions

Use `python-dateutil = "^2.8.2"` in `pyproject.toml` instead of the strict `2.8.2` specification

**Comment by GaspardBT** [comment]
Thanks for opening this issue, we implemented the suggested solution and it is available in `1.2.5`
Closing the issue but feel free to reopen it, if the issue persist 👍
