### ISSUE TITLE
docs: guardrailing missing

### ISSUE THREAD

**Issue by Huge** [mistralai/client-python#17]
Link leading to https://docs.mistral.ai/platform/overview/guardrailing shows 404

**Comment by Bam4d** [comment]
Where is this link in the python client?

**Comment by eskayML** [comment]
@Bam4d the link can be found in the documentation on this page
https://docs.mistral.ai/platform/overview/


That guardrailing url returns the error 404

I'll assume the mistake team are still working on it as an entire feature though

**Comment by Bam4d** [comment]
This link is now fixed.

**Comment by Huge** [comment]
It seems to me that https://docs.mistral.ai/platform/overview/ still links to  https://docs.mistral.ai/platform/overview/guardrailing which is a different link than @Bam4d provided.

I have checked  in Chrome incognito, but still a slight chance caching might mislead me in this observation.
