### ISSUE TITLE
Add method to count tokens

### ISSUE THREAD

**Issue by sbarman25** [mistralai/client-python#21]
Is it possible to add `get_num_tokens(prompt)` function to the SDK?

Thanks.

**Comment by fsndzomga** [comment]
Would be nice indeed. For now I still use tiktoken. I think it still gives a kinda good estimate even if it doesn't match the usage info we get in the response object.

```
import tiktoken

def num_tokens_from_string(string: str) -> int:
        encoding = tiktoken.get_encoding("cl100k_base")
        num_tokens = len(encoding.encode(string))
        return num_tokens

```

**Comment by Bam4d** [comment]
FYI we added a usage page to the dashboard which can help track your usage:
https://console.mistral.ai/user/usage/

**Comment by ishaan-jaff** [comment]
Hi @sbarman-mi9 @fsndzomga @Bam4d  I'm the maintainer of LiteLLM https://github.com/BerriAI/litellm we allow you to do cost tracking for 100+ LLMs - [We support the mistral ai api]

## Usage
Docs: https://docs.litellm.ai/docs/#calculate-costs-usage-latency
```python
from litellm import completion, completion_cost
import os
os.environ["MISTRAL_API_KEY"] = "your-api-key"

response = completion(
  model="mistral/mistral-medium", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)

cost = completion_cost(completion_response=response)
print("Cost for completion call with mistral/mistral-medium: ", f"${float(cost):.10f}")
```

We also allow you to create a self hosted OpenAI Compatible proxy server to make your LLM calls (100+ LLMs), track costs, token usage 
Docs: https://docs.litellm.ai/docs/simple_proxy 

I hope this is helpful, if not I'd love your feedback on what we can improve

**Comment by fsndzomga** [comment]
thanks @ishaan-jaff ! I checked your package and it's really nice. What do you use to count tokens ? Tiktoken I guess ?
