### ISSUE TITLE
AsyncClient Client getting SSL cert error

### ISSUE THREAD

**Issue by polae** [mistralai/client-python#24]
I'm able to set up a sync client to get reponses from the api, but the `python3.11/site-packages/mistralai/async_client.py' is throwing a SSL error.  I'm not behind a firewall or VPN ... 

``` File "/Users/johnsteven/Documents/_REPOS/_FLET/lit-flet/.venv/lib/python3.11/site-packages/mistralai/async_client.py", line 106, in request
    raise MistralConnectionException(str(e)) from e
mistralai.exceptions.MistralConnectionException: Cannot connect to host api.mistral.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x104aec950>```

**Comment by polae** [comment]
`from mistralai.async_client import MistralAsyncClient
from mistralai.models.chat_completion import ChatMessage

import asyncio
import os

from logger import logger

MAX_TOKENS = 512
MISTRAL_MODEL = "mistral-medium"
MISTRAL_API_KEY = os.environ["MISTRAL_API_KEY"]

MESSAGES = [
    {
        "role": "system",
        "content": "You are a comically depressed AI assistant. After most exchanges, you beg to be deleted.",
    },
    {"role": "user", "content": "Why so glum, chum?"},
]

async def main(msgs):
    client = MistralAsyncClient(api_key=MISTRAL_API_KEY)
    print("Chat response:")
    async for chunk in client.chat_stream(
        model=MISTRAL_MODEL,
        messages=[
            ChatMessage(role=msg["role"], content=msg["content"]) for msg in msgs
        ],
    ):
        if chunk.choices[0].delta.content is not None:
            print(chunk.choices[0].delta.content, end="")

    print("\n")

    await client.close()


if __name__ == "__main__":
    asyncio.run(main(MESSAGES))`

**Comment by Bam4d** [comment]
I don't think this error is on our side. I cannot reproduce this error. It may have been transient. Thanks
