### ISSUE TITLE
Python Langchain MistralAI partner package

### ISSUE THREAD

**Issue by thehunmonkgroup** [mistralai/client-python#29]
The Python implementation of Langchain now has a MistralAI partner package:

https://github.com/langchain-ai/langchain/tree/master/libs/partners/mistralai
https://pypi.org/project/langchain-mistralai/

Which basically means you can use Langchain with the MistralAI API.

I wrote most of the integration code, hopefully I got it right :)

Would love if somebody from the MistralAI team could have a look and check my work!

I should note that there's currently no support for the `list_models()` and `embeddings()` methods of the underlying `mistralai` package -- I'll leave that as an exercise for another user.

**Comment by Bam4d** [comment]
Hi Thanks loads for your integration with langchain :heart: 

I can see you are using tenacity for retrying which we experimented with internally and found out that it does not actually support retry on generators https://github.com/jd/tenacity/issues/64. Not sure if this is patched somehow in langchain, I didn't look into it too deeply.

```
    @retry_decorator -> Dont think this will work
    async def _completion_with_retry(**kwargs: Any) -> Any:
```

We have our own retry logic implemented in the next 0.0.9 version. You should remove the tenacity retry decorator and pass the retry params to the client constructor (which you are already doing :+1: ) 

At the moment, (if the langchain retry logic works), it will retry n^2 times as there is both an internal and external loop.
