### ISSUE TITLE
pip install mistralai ends with errors

### ISSUE THREAD

**Issue by delip** [mistralai/client-python#3]
![image](https://github.com/mistralai/client-python/assets/347398/08625897-4d11-4ba1-9097-f21fcbad3f88)

**Comment by ahmetkca** [comment]
Is there a standalone client python package? or do you have to clone this repository to be able to use MistralAI client?

**Comment by shamikbose** [comment]
@delip I was able to get this working with poetry
```
poetry shell
pip install mistralai
```
but having a standalone package would be much easier to use for developers

**Comment by Bam4d** [comment]
Hey, you only need poetry if you are installing from source.

You can use `pip install mistralai` like you would in any other environment such as venv or conda.

I will update the documentation to make this clearer.

Thanks!

**Comment by chottuthejimmy** [comment]
@delip Mate Please Please reply to my mentorship application. I have hustled a lot and tried everything I could. Please mate 🙏
