### ISSUE TITLE
DOCS: Missing import in python client example

### ISSUE THREAD

**Issue by iandanforth** [mistralai/client-python#32]
For the python example: https://docs.mistral.ai/platform/client there is a missing `import os`.

**Comment by iandanforth** [comment]
Note: I wasn't able to find the source for the docs, so posting here. I'll close and re-open elsewhere if a dev can point me in the right direction

**Comment by Bam4d** [comment]
The source of the docs is now public and can be found here: https://github.com/mistralai/platform-docs-public
