### ISSUE TITLE
Handling rate limits with mistral-embed

### ISSUE THREAD

**Issue by chris-park** [mistralai/client-python#34]
I've been working on embedding a large document with `mistral-embed` and have repeatedly reached the API rate limit (2M tokens/min). Could you provide any advice or best practices for managing these limits more effectively when using the Python client?

Appreciate your guidance.

**Comment by sophiamyang** [comment]
Hi @chris-park, thanks for the issue report. You can request rate limit increase with our support chatbot on la Plateforme.
