### ISSUE TITLE
Remains in Waiting State on Windows 10， Linux system works

### ISSUE THREAD

**Issue by socamalo** [mistralai/client-python#35]
## Environment
- OS: Windows 10
- Mistral version: [0.0.9]
- Python version: [3.11]
- Poetry version: [mistralai 0.0.1]

## Description
I am encountering an issue where Mistral remains in a waiting state indefinitely on Windows 10. This happens after I've modified the import section of my code to include `pyreadline3`. Despite successfully installing `pyreadline3` and using `poetry` as my dependency manager, Mistral does not proceed to an active state.

 Steps to Reproduce
1. Added the following lines at the beginning of my Python script:
   ```python
   from pyreadline3 import Readline
   readline = Readline()

2、Installed pyreadline3 using poetry add pyreadline3.
3、Ran the script expecting Mistral to be functional.

Expected Behavior
Mistral should run as expected, similar to its behavior on a Linux system.

Actual Behavior
Mistral stays in a waiting state and does not proceed to execute any further actions.

Additional Context
The same codebase works without issues on a Linux environment.
Using the requests library to perform POST requests, I am able to receive responses from Mistral, which indicates that the API and network connections are functioning correctly.
Attempts to Fix
Ensured that pyreadline3 is properly installed and accessible within the poetry environment.
Ran the script with administrative privileges to rule out permission issues.
I would appreciate any guidance or suggestions on how to resolve this issue.

**Comment by Bam4d** [comment]
I'm not sure I can help as I'm not sure if this issue is related to mistral or to the pyreadline3 library.

Does your code work if you remove the `Readline()` part of the code?

**Comment by sophiamyang** [comment]
Closing the issue as it's inactive
