### ISSUE TITLE
Client Documentation and Ruby Implementations

### ISSUE THREAD

**Issue by gbaptista** [mistralai/client-python#36]
Sorry if this is the wrong place to open an issue about this.

Is the documentation open source? https://docs.mistral.ai/platform/client/

I would like to propose adding these two implementations to the 'Third-Party Clients' section:
- Ruby Client: https://github.com/gbaptista/mistral-ai
- CLI Multi-Provider Client: https://github.com/icebaker/ruby-nano-bots

**Comment by fsndzomga** [comment]
And here is another Ruby Client: https://github.com/fsndzomga/mistral_rb

**Comment by Bam4d** [comment]
Hi! You can add pull requests for docs to the (now) public docs repo here: https://github.com/mistralai/platform-docs-public
