### ISSUE TITLE
MistralAI python client package

### ISSUE THREAD

**Issue by ahmetkca** [mistralai/client-python#4]
What's the name of the python package? Or do you have to clone this repository to be able to use the MistralAI python client?

**Comment by code-inflation** [comment]
Should be `mistralai` I think: https://pypi.org/project/mistralai/

**Comment by ahmetkca** [comment]
yeah I think it has to be in the README file imo #5

**Comment by code-inflation** [comment]
For sure!

**Comment by Bam4d** [comment]
Hi, sorry for the confusion on this. 

You can simply use `pip install mistralai` in any environment such as conda or venv. 

You only require the poetry dependencies when building the package from source.

Thanks!
