### ISSUE TITLE
Add stop sequence parameter for controlled generation

### ISSUE THREAD

**Issue by Itinte** [mistralai/client-python#41]
**Description**:

It would be valuable to include a stop sequence parameter in the API client to facilitate controlled generation termination.

**Reference Implementation**:
Referencing OpenAI's implementation, please check: [OpenAI API Reference - Chat Create Stop](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop)

**Use Case**:
This feature becomes crucial when working with agents, allowing users to halt generation at precise steps

[discord topic](https://discord.com/channels/1144547040454508606/1184330074992943175)

**Comment by sbarman-mi9** [comment]
I second this. It's much needed.

**Comment by yquemener** [comment]
Adding to this. For now that limits my usage of Mistral API. I have tons of requests to do with very short yes/no answers. For now local hosting is my only solution sadly.

**Comment by failable** [comment]
Any updates?
