### ISSUE TITLE
Mistral token counting/batching

### ISSUE THREAD

**Issue by pbeart** [mistralai/client-python#46]
Hi, I'm interested in making a PR so that the embedding methods chunk data to ensure each request has less than the maximum (16384) required by Mistral. Unfortunately, there doesn't seem to be a lightweight way to count tokens for Mistral, such as `tiktoken` for OpenAI models - I guess most of the time it's going to be safe to use tiktoken with a safety margin, but is there a way to count tokens accurately without a heavy library?

**Comment by sophiamyang** [comment]
We have published our tokenizers. You can use `mistral-common` to count tokens. Details here: https://docs.mistral.ai/guides/tokenization/
