### ISSUE TITLE
Please provide a head start for cli/api context-history management, suggestion provided here.

### ISSUE THREAD

**Issue by lineality** [mistralai/client-python#51]
Hello. I just signed up for Mistral api, it is very exciting. 
And at docs.mistral.ai/
I saw the provided code for connecting with the api is not so verbose; one block of the curl.

It may be helpful for your python-using users to have a user-friendly way to get started with the AI
and the longer road of managing context history. So

Here is a colab for basic history management and recording. Sorry it is very crud but,
please use it if people find it useful.
https://github.com/lineality/simple_mistral_api_context_history_manager

You are very important, thank you for your work.

**Comment by lineality** [comment]
Sorry, I cannot tell if the file on github saved correctly, a colab link is here: 
https://colab.research.google.com/drive/1cRQNH0JrM9IkiOgOy9kQijUSEtwlYNj1

**Comment by sophiamyang** [comment]
Thanks so much for the example. Would you be interested in submitting your example to our cookbook? It'd be great for our cookbook: https://github.com/mistralai/cookbook
