### ISSUE TITLE
Got "chat() got an unexpected keyword argument 'response_format' " while using the JSON mode 

### ISSUE THREAD

**Issue by liujuncn** [mistralai/client-python#63]
I got an error message saying 'chat() got an unexpected keyword argument 'response_format'' while using the JSON mode example in my Python code according to the documentation.

**Comment by aanaseer** [comment]
I've run the JSON mode example from the [documentation](https://docs.mistral.ai/platform/client/#json-mode) and it appears to be working as expected with v0.1.3. I would suggest checking the version of client you are using. It might be v0.0.12 or earlier resulting in the error.

**Comment by liujuncn** [comment]
> I've run the JSON mode example from the [documentation](https://docs.mistral.ai/platform/client/#json-mode) and it appears to be working as expected with v0.1.3. I would suggest checking the version of client you are using. It might be v0.0.12 or earlier resulting in the error.

You are correct. The client version installed from 'pip install mistralai' is 0.0.12. To use a newer version, is it necessary to install from the source code?

**Comment by aanaseer** [comment]
> You are correct. The client version installed from 'pip install mistralai' is 0.0.12. To use a newer version, is it necessary to install from the source code?

Your Python version might be 3.8 or older. Version >= 0.1.2 of `mistralai` requires Python 3.9 or newer. So if you upgrade Python in your dev environment and `pip install mistralai` it should work.
