### ISSUE TITLE
Make orjson an optional dependency

### ISSUE THREAD

**Issue by Zaczero** [mistralai/client-python#71]
Thank you for your work! Can we please make orjson dependency optional? I have concerns about the quality of this dependency (compatibility, security) and would prefer to not use it in my projects.

For example https://github.com/ijl/orjson/issues/452 talks about python segfault that was introduced in one of the releases, and it took multiple iterations to get it fixed properly:

- https://github.com/ijl/orjson/pull/457
- https://github.com/ijl/orjson/pull/459

You will also see that this project has 1-week stale auto-close policy, which is yet another red flag for me.

See:

- https://github.com/ijl/orjson/issues/460
- https://github.com/ijl/orjson/issues/461
- and the list goes on and on...

My suggestion would be to drop the orjson dependency in exchange for https://jcristharif.com/msgspec and made it optional, just for the people who really need it - the performance gain [here](https://github.com/mistralai/client-python/blob/80c7951bad83338641d5e89684f841ce1cac938f/src/mistralai/client_base.py#L128) is most likely very small and for many people it's probably not worth the additional dependency/risk. We are not parsing megabytes/gigabytes of data - stdlib's json should do pretty well.

**Comment by sophiamyang** [comment]
Thanks for reporting the issue. I don't think orjson is a dependency anymore according to https://github.com/mistralai/client-python/blob/main/pyproject.toml. Please let us know if you see more issues. Thanks!

**Comment by Zaczero** [comment]
Indeed it is not
