### ISSUE TITLE
Make httpx dependency version less restrictive

### ISSUE THREAD

**Issue by Zaczero** [mistralai/client-python#73]
Can we please replace

```txt
httpx = "^0.25.2"
```

with

```txt
httpx = "<1"
```

The lock on 0.25.* is very restrictive and httpx development is backwards compatible (assuming major version remains unchanged). <1 will lock on 0.*, allowing for safe minor version incremental.

```txt
mistralai 0.1.6
├── httpx >=0.25.2,<0.26.0
```

**Comment by dbrewster** [comment]
Second that please. Would a PR help?

**Comment by Mastikosa** [comment]
Same issue. There is a conflict with another library used in our project.

**Comment by FAbrahamDev** [comment]
+1
