### ISSUE TITLE
Custom logging level results in error upon importing client

### ISSUE THREAD

**Issue by MarvinGrNoota** [mistralai/client-python#75]
## Description

Using a custom logging level e.g. `TRACE` results in an `ValueError` when `client_base.py` is imported.

In [`client_base.py`](https://github.com/mistralai/client-python/blob/80c7951bad83338641d5e89684f841ce1cac938f/src/mistralai/client_base.py#L13-L16) the logging level is configured by reading the `LOG_LEVEL`. The level parameter of the stdlib logging may only be [DEBUG, INFO, WARNING, ERROR, CRITICAL or NOTSET](https://docs.python.org/3/library/logging.html#logging-levels) thus resulting in an error when using a different log level.

## Example

```python
import os
os.environ["LOG_LEVEL"] = "TRACE"
from mistralai import client_base # ValueError: Unknown level: 'TRACE'
```

**Comment by fuegoio** [comment]
Fixed by #86. Thanks for reporting this issue!
