### ISSUE TITLE
Here is a Golang implementation

### ISSUE THREAD

**Issue by sam-ulrich1** [mistralai/client-python#8]
I made a golang implementation. Credit where it's due, a lot of the code was generated with GPT 4 but I cleaned everything up and added tests

https://github.com/Gage-Technologies/mistral-go

**Comment by sam-ulrich1** [comment]
If y'all want to in-house the codebase so you control it feel free. I'll still contribute

**Comment by Bam4d** [comment]
Thanks loads for this. I'll add a reference to third party SDKs in our docs and point to your repo? You should get all the stars for this not us ❤️
