### ISSUE TITLE
FYI: We are working on a client using posix shell/awk/curl

### ISSUE THREAD

**Issue by edwinjhlee** [mistralai/client-python#89]
Hi mistral community,

We are working on the mistral API client in x-cmd.
x-cmd is a tool built with shell/awk and can leverage 500 portable pkgs.

https://x-cmd.com/mod/mistral

Users need to  setup the token using 'x mistral init', then can use `x mistral` or `@mistral` in the command line.

We are also working on implementation of a local model management solution leveraging llamafile.

https://x-cmd.com/mod/llmf

Thanks you for your work in open source models.

Regards,
Li Junhao
l@x-cmd.com
24-05-14

**Comment by sophiamyang** [comment]
Thanks for the cool example! Please feel free to contribute an example to our cookbook: https://github.com/mistralai/cookbook/.
